# Generated by Django 4.1.1 on 2022-09-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'book_db',
                'managed': False,
            },
        ),
    ]
